name: Build and Push Docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "hossammahmoud007" --password-stdin

      - name: Build Docker image
        run: docker build -t hossammahmoud007/node-app .

      - name: Push Docker image
        run: docker push hossammahmoud007/node-app
